### ISSUE TITLE
Incompatible with Haxe 4

### ISSUE THREAD

**Issue by DevRubicate** [ibilon/webgl2#1]
Haxe 4 has changed a lot of the JS stuff from **js.html.*** to **js.lib.*** so this library no longer works as-is.

**Comment by ibilon** [comment]
Shouldn't be too hard to fix, I'll take a look this week.

**Comment by ibilon** [comment]
That was a lot easier than I thought, those were only warnings, though a huge number of it.
Uploaded version 1.2.0 to haxelib.
Thanks for reporting the issue.
